import './rope.mjs';
import './transformation.mjs';
import './rewind.mjs';
import './interface.mjs';
import './performance.mjs';
import './stonework-skyhook.mjs';
import './goal-impact.mjs';
import './lever-action-air-mail.mjs';
import './express-elevator-ejection.mjs';
import './rocket-canopy-relay.mjs';
import './pendulum-bank-exchange.mjs';
import './cloudstone-customs.mjs';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {blankLevel,makePart,parseLevel,PARTS} from '../dist/model.js';
import {createWorld,stepWorld,connectionPoints,pathLength,overlaps} from '../dist/physics.js';
import {Workshop} from '../dist/workshop.js';
const simulate=(world,seconds)=>{for(let i=0;i<seconds*120;i++)stepWorld(world);return world;};
const solveTime=(world,seconds=20,afterStep)=>{for(let frame=1;frame<=seconds*120;frame++){const events=stepWorld(world);afterStep?.(world,events,frame);if(world.won)return frame/120;}return null;};
const overlapPairs=(world,includeSensors=false)=>{const pairs=[];for(let i=0;i<world.bodies.length;i++)for(let j=i+1;j<world.bodies.length;j++)if((includeSensors||!PARTS[world.bodies[i].kind].sensor&&!PARTS[world.bodies[j].kind].sensor)&&overlaps(world.bodies[i],world.bodies[j]))pairs.push([world.bodies[i].id,world.bodies[j].id]);return pairs;};
const insideBucket=(world,bodyId,bucketId)=>{const body=world.bodies.find(body=>body.id===bodyId),bucket=world.bodies.find(body=>body.id===bucketId);return Math.abs(body.x-bucket.x)<bucket.w/2-12&&body.y>bucket.y-bucket.h/2&&body.y<bucket.y+bucket.h/2-8;};
const scene=(bodies,connections=[],environment={})=>({...blankLevel(),bodies,connections,environment:{width:1600,height:1000,gravity:850,pressure:0,floor:false,...environment}});
const part=(kind,x,y,properties={})=>makePart(kind,x,y,properties);
{
  const world=createWorld(scene([part('box',300,200)]));simulate(world,.5);assert.ok(Math.abs(world.bodies[0].vy-425)<1e-6);assert.ok(world.bodies[0].y>300);assert.equal(world.bodies[0].omega,0);
}
{
  const world=createWorld(scene(Array.from({length:4},(_,i)=>part('box',800,915-i*50,{w:80,h:50})),[],{floor:true}));simulate(world,20);assert.ok(world.bodies.every(b=>Math.abs(b.x-800)<3));
}
{
  const world=createWorld(scene([part('circle',110,300,{w:12,h:12,material:'steel'}),part('ramp',160,300,{w:12,h:300})],[],{gravity:0}));world.bodies[0].vx=2200;stepWorld(world,.1);assert.ok(world.bodies[0].vx<0);assert.ok(world.bodies[0].x<160);
}
{
  const bodies=[part('motor',100,300,{id:'motor',on:false,power:3,direction:-1}),part('wheel',300,300,{id:'wheel'}),part('conveyor',500,300,{id:'belt'})];
  const connections=[{id:'b1',kind:'belt',a:'wheel',b:'belt',length:200},{id:'b2',kind:'belt',a:'wheel',b:'motor',length:200}];
  const world=createWorld(parseLevel(scene(bodies,connections)));stepWorld(world);assert.equal(world.bodies[2].active,false);world.bodies[0].on=true;stepWorld(world);assert.equal(world.bodies[2].active,true);assert.equal(world.bodies[2].power,3);assert.equal(world.bodies[2].direction,-1);assert.ok(world.bodies[1].omega<0);
  const bad=scene(bodies,[...connections,{id:'b3',kind:'belt',a:'b1',b:'motor'}]);assert.throws(()=>parseLevel(bad),/endpoints/);
  bad.connections=connections;bad.goal={kind:'state',target:'b1'};assert.throws(()=>parseLevel(bad),/target/);
}
{
  const world=createWorld(parseLevel(scene([part('circle',100,260,{id:'a',w:30}),part('pulley',250,100,{id:'p'}),part('circle',400,260,{id:'b',w:30})],[{id:'r',kind:'rope',a:'a',b:'b',via:['p'],length:300}],{gravity:0})));simulate(world,1);assert.ok(Math.abs(pathLength(connectionPoints(world,world.connections[0]))-300)<.1);
}
{
  const world=createWorld(parseLevel(scene([part('switch',200,300,{id:'s'}),part('circle',200,300),part('rocket',600,300,{id:'r'})],[{id:'wire',kind:'wire',a:'s',b:'r'}],{gravity:0})));stepWorld(world);stepWorld(world);assert.equal(world.bodies[2].state,'fired');assert.ok(world.bodies[2].vy<0);
}
{
  const baseline=blankLevel();assert.throws(()=>parseLevel({...baseline,bodies:[{id:'x',kind:'toString',x:0,y:0}]}),/component/i);assert.throws(()=>parseLevel({...baseline,inventory:[null]}),/Inventory/);assert.throws(()=>parseLevel({...baseline,inventory:[{id:'stock',part:part('box',0,0),quantity:1.5}]}),/whole/);
  const workshop=new Workshop(scene([part('circle',400,200,{id:'ball'})]));workshop.selected='ball';workshop.update({x:500});assert.equal(workshop.world.bodies[0].x,500);workshop.undo();assert.equal(workshop.world.bodies[0].x,400);workshop.redo();assert.equal(workshop.world.bodies[0].x,500);workshop.reset();assert.equal(workshop.world.bodies[0].x,500);
}
{
  assert.ok(Object.values(PARTS).every(component=>typeof component.resizable==='boolean'),'Every inventory component must declare its sizing policy');assert.deepEqual(Object.entries(PARTS).filter(([,component])=>component.resizable).map(([kind])=>kind),['circle','box','material-zone']);
  const baseline=blankLevel();assert.throws(()=>parseLevel({...baseline,bodies:[part('rocket',300,200,{id:'oversized-rocket',resizable:true})]}),/fixed size/);assert.throws(()=>parseLevel({...baseline,bodies:[part('circle',300,200,{id:'bad-resize',resizable:'yes'})]}),/resizable/);
  const sandbox=new Workshop(scene([part('circle',300,200,{id:'generic'}),part('rocket',600,200,{id:'special'})]));assert.equal(sandbox.canResize(sandbox.world.bodies[0]),true);assert.equal(sandbox.canResize(sandbox.world.bodies[1]),false);sandbox.selected='special';assert.throws(()=>sandbox.update({w:64}),/fixed size/);sandbox.selected='generic';sandbox.update({w:80,h:80});assert.equal(sandbox.body().w,80);
  const editor=new Workshop({...scene([part('rocket',300,200,{id:'author-rocket'})]),mode:'editor'});editor.selected='author-rocket';assert.equal(editor.canResize(editor.body()),true);editor.update({w:64,h:96});assert.deepEqual([editor.body().w,editor.body().h],[64,96]);
  const sizedPuzzle=parseLevel({...scene([part('bell',1200,200,{id:'size-goal'})]),mode:'puzzle',inventory:[{id:'small-circle',part:part('circle',0,0,{w:30,h:30}),quantity:1},{id:'large-circle',part:part('circle',0,0,{w:70,h:70}),quantity:1}],goal:{kind:'state',target:'size-goal',state:'rung'}});assert.deepEqual(sizedPuzzle.inventory.map(entry=>[entry.part.w,entry.part.resizable]),[[30,false],[70,false]],'Puzzle authors may supply multiple fixed-size variants');const puzzleWorkshop=new Workshop(sizedPuzzle),small=puzzleWorkshop.newPart('circle',300,200,{},'small-circle'),large=puzzleWorkshop.newPart('circle',500,200,{},'large-circle');assert.deepEqual([small.w,large.w],[30,70]);puzzleWorkshop.insert(small);puzzleWorkshop.selected=small.id;assert.throws(()=>puzzleWorkshop.update({w:40}),/fixed size/);puzzleWorkshop.play();assert.equal(puzzleWorkshop.editable(puzzleWorkshop.body()),false);assert.throws(()=>puzzleWorkshop.update({x:400}),/Reset the puzzle/);assert.throws(()=>puzzleWorkshop.newPart('circle',500,200,{},'large-circle'),/Reset the puzzle/);puzzleWorkshop.pause();assert.equal(puzzleWorkshop.running,false);assert.throws(()=>puzzleWorkshop.update({x:400}),/Reset the puzzle/);assert.throws(()=>puzzleWorkshop.undo(),/Reset the puzzle/);puzzleWorkshop.reset();puzzleWorkshop.selected=small.id;puzzleWorkshop.update({x:400});assert.equal(puzzleWorkshop.body().x,400);puzzleWorkshop.undo();assert.equal(puzzleWorkshop.body().x,300);
}
const pack=JSON.parse(await readFile(new URL('../dist/levels.json',import.meta.url))),solutions=JSON.parse(await readFile(new URL('./solutions.json',import.meta.url)));
const pulleyLevels=new Map([
  ['bellhop-express',4.95],
  ['two-to-one-takeaway',1.0583333333333333],
  ['pulley-gate-night-shift',1.8916666666666666],
]);
const transformationLevels=new Map([
  ['featherweight-freight',{seconds:14,wonAt:4.941666666666666,ball:'freight-ball',stock:'freight-route',original:'steel',transforms:['cork'],ablations:[
    ['Steel ball must be too heavy for the fan',level=>{level.bodies.find(body=>body.id==='feather-zone').outputMaterial='steel';}],
    ['Featherweight Freight must need its fan',level=>{level.bodies.find(body=>body.id==='freight-fan').on=false;}],
  ]}],
  ['cloud-then-clunk',{seconds:14,wonAt:9.058333333333334,ball:'weather-ball',stock:'weather-route',original:'steel',transforms:['cork','steel'],ablations:[
    ['Cloud, Then Clunk must need its fan',level=>{level.bodies.find(body=>body.id==='updraft').on=false;}],
    ['Cloud, Then Clunk must need its first zone',level=>{level.bodies.find(body=>body.id==='cloud-zone').outputMaterial='steel';}],
    ['Cloud, Then Clunk must need its second zone',level=>{level.bodies.find(body=>body.id==='clunk-zone').outputMaterial='cork';}],
    ['Cloud, Then Clunk must need its rope',level=>{level.connections=[];}],
  ]}],
  ['rubber-stamp',{seconds:12,wonAt:5.816666666666666,ball:'stamp-ball',stock:'stamp-route',original:'steel',transforms:['rubber'],angleDelta:.025,ablations:[
    ['Steel must not rebound high enough',level=>{level.bodies.find(body=>body.id==='rubber-zone').outputMaterial='steel';}],
    ['Rubber Stamp must need its bounce plate',level=>{level.bodies=level.bodies.filter(body=>body.id!=='bounce-plate');}],
  ]}],
  ['the-sky-is-falling',{seconds:12,wonAt:3.408333333333333,ball:'sky-balloon',stock:'crosswind',original:'helium',transforms:['steel'],angleDelta:.03,reverses:true,baseline:[
    ['Unassisted balloon must miss Turn to Stone',world=>world.bodies.find(body=>body.id==='sky-balloon').transformedZones.length===0],
    ['Unassisted balloon must miss the switch',world=>world.bodies.find(body=>body.id==='stone-switch').state!=='on'],
    ['Unassisted rocket must remain off',world=>world.bodies.find(body=>body.id==='message-rocket').state!=='fired'],
  ],milestones:[
    ['Fan must route the balloon through Turn to Stone',1.2916666666666667,(_world,events)=>events.some(event=>event.kind==='transform')],
    ['Stone balloon must land on the switch',2.691666666666667,world=>world.bodies.find(body=>body.id==='stone-switch').state==='on'],
    ['Wire must fire the rocket after the switch',2.7,world=>world.bodies.find(body=>body.id==='message-rocket').state==='fired'],
  ],ablations:[
    ['The Sky Is Falling must need its fan',level=>{level.bodies.find(body=>body.stock==='crosswind').on=false;}],
    ['The Sky Is Falling must need its stone zone',level=>{level.bodies=level.bodies.filter(body=>body.id!=='stone-cloud');}],
    ['The Sky Is Falling must need its wire',level=>{level.connections=[];}],
    ['The Sky Is Falling must need rocket power',level=>{level.bodies.find(body=>body.id==='message-rocket').power=0;}],
  ]}],
  ['stone-balloon',{seconds:12,wonAt:2.75,ball:'ballast-balloon',stock:'stone-zone',original:'helium',transforms:['steel'],zones:['placed-stone-zone'],positionDelta:20,angleDelta:.05,reverses:true,reversalAt:1.3333333333333333,includeSensors:true,rope:'exchange-rope',baseline:[
    ['Without the placed zone, the balloon must remain helium',world=>world.bodies.find(body=>body.id==='ballast-balloon').material==='helium'],
  ],milestones:[
    ['The rising balloon must enter Turn to Stone',.6083333333333333,(_world,events)=>events.some(event=>event.kind==='transform')],
  ],ablations:[
    ['Stone Balloon must need its rope',level=>{level.connections=[];}],
    ['Cork must be too light to reverse the counterweight',level=>{level.bodies.find(body=>body.stock==='stone-zone').outputMaterial='cork';}],
    ['Stone Balloon must need the zone on the balloon route',level=>{level.bodies.find(body=>body.stock==='stone-zone').x=650;}],
  ]}],
  ['upward-mobility',{seconds:8,wonAt:4.208333333333333,ball:'freight-parcel',stock:'helium-zone',original:'steel',transforms:['helium'],zones:['placed-helium-zone'],includeSensors:true,variants:[['x',-20],['x',20],['y',-8],['y',8],['angle',-.03],['angle',.03]],baseline:[
    ['Empty-bin parcel must remain steel',world=>world.bodies.find(body=>body.id==='freight-parcel').material==='steel'],
    ['Empty bin must not transform the parcel',world=>world.bodies.find(body=>body.id==='freight-parcel').transformedZones.length===0],
  ],milestones:[
    ['Conveyor must deliver the parcel into the placed zone',3.35,(_world,events)=>events.some(event=>event.kind==='transform')],
    ['Helium parcel must rise into the overhead bell',4.208333333333333,world=>world.bodies.find(body=>body.id==='air-bell').state==='rung'],
  ],ablations:[
    ['Upward Mobility must need its material zone',level=>{level.bodies=level.bodies.filter(body=>body.stock!=='helium-zone');}],
    ['Upward Mobility must need its conveyor',level=>{level.bodies.find(body=>body.id==='freight-belt').on=false;}],
    ['Upward Mobility must need the conveyor direction',level=>{level.bodies.find(body=>body.id==='freight-belt').direction=1;}],
    ['Cork must not rise into the bell',level=>{level.bodies.find(body=>body.stock==='helium-zone').outputMaterial='cork';}],
    ['Upward Mobility must need atmospheric pressure',level=>{level.environment.pressure=0;}],
  ]}],
]);
assert.equal(solutions.length,pack.levels.length,'Every playable level needs one reference solution');
for(const [i,level] of pack.levels.entries()){
  const authored=parseLevel(level);assert.ok(authored.bodies.every(body=>body.resizable===false),`${level.name}: puzzle bodies must have fixed authored sizes`);assert.ok(authored.inventory.every(entry=>entry.part.resizable===false),`${level.name}: puzzle inventory must have fixed authored sizes`);assert.equal(simulate(createWorld(authored),20).won,false,`${level.name}: empty bin must fail`);
  if(authored.goal.kind==='state'&&['rung','on','popped'].includes(authored.goal.state))assert.ok(authored.goal.hitBy?.length,`${level.name}: state goal must name its valid impact source`);
  const solved=parseLevel({...level,bodies:[...level.bodies,...solutions[i].parts.map(p=>part(p.kind,p.x,p.y,p))]});const world=simulate(createWorld(solved),20);assert.equal(world.won,true,`${level.name}: reference solution must win`);
  const again=parseLevel(JSON.parse(JSON.stringify(solved)));assert.deepEqual(again.bodies,solved.bodies);assert.deepEqual(again.connections,solved.connections);assert.deepEqual(again.goal,solved.goal);assert.deepEqual(again.inventory,solved.inventory);
  if(level.id==='pulley-gate'){
    for(const omitted of ['drop-weight','rope','movable']){const blocked=structuredClone(solved);if(omitted==='drop-weight')blocked.bodies=blocked.bodies.filter(b=>b.id!==omitted);if(omitted==='rope')blocked.connections=[];if(omitted==='movable')blocked.bodies.find(b=>b.id==='movable-pulley').pinned=true;assert.equal(simulate(createWorld(blocked),20).won,false,`Door must need ${omitted}`);}
    for(const [dx,da] of [[-8,0],[8,0],[0,-.03],[0,.03]]){const nearby=structuredClone(solved),ramp=nearby.bodies.find(b=>b.stock);ramp.x+=dx;ramp.angle+=da;assert.equal(simulate(createWorld(nearby),20).won,true,'Nearby ramp placement must work');}
    const reset=new Workshop(solved),first=simulate(reset.world,8);const outcome=structuredClone(first);reset.reset();assert.deepEqual(simulate(reset.world,8),outcome);
  }
  if(pulleyLevels.has(level.id)){
    const noRope=structuredClone(solved);noRope.connections=[];assert.equal(simulate(createWorld(noRope),20).won,false,`${level.name}: solution must need its rope`);
    assert.deepEqual(overlapPairs(createWorld(solved)),[],`${level.name}: reference must start without overlaps`);
    const reset=new Workshop(solved),expected=pulleyLevels.get(level.id),first=solveTime(reset.world);assert.equal(first,expected,`${level.name}: solve time changed`);reset.reset();assert.equal(solveTime(reset.world),first,`${level.name}: reset changed solve time`);
    for(let partIndex=0;partIndex<solutions[i].parts.length;partIndex++)for(const [field,delta] of [['x',-6],['x',6],['y',-6],['y',6]]){
      const parts=structuredClone(solutions[i].parts);parts[partIndex][field]+=delta;const nearby=parseLevel({...level,bodies:[...level.bodies,...parts.map(p=>part(p.kind,p.x,p.y,p))]}),nearbyWorld=createWorld(nearby);
      assert.deepEqual(overlapPairs(nearbyWorld),[],`${level.name}: nearby ${parts[partIndex].id} must not overlap`);assert.notEqual(solveTime(nearbyWorld),null,`${level.name}: nearby ${parts[partIndex].id} ${field} ${delta} must win`);
    }
  }
  if(level.id==='rock-delivery'){
    const withoutRope=structuredClone(solved);withoutRope.connections=[];assert.equal(simulate(createWorld(withoutRope),12).won,false,'Rock Delivery must need its rope');
    const unchanged=structuredClone(solved);unchanged.bodies.find(body=>body.id==='stone-zone').outputMaterial='cork';const unchangedWorld=simulate(createWorld(unchanged),12);assert.equal(unchangedWorld.won,false,'Cork must be too light');assert.equal(insideBucket(unchangedWorld,'delivery-ball','stone-bucket'),true,'Unchanged cork must reach the bucket');
    const disabled=structuredClone(solved);disabled.bodies=disabled.bodies.filter(body=>body.id!=='stone-zone');const disabledWorld=simulate(createWorld(disabled),12);assert.equal(disabledWorld.won,false,'Disabled zone must fail');assert.equal(insideBucket(disabledWorld,'delivery-ball','stone-bucket'),true,'Ball must reach the bucket without transformation');
    const bypass=structuredClone(solved);Object.assign(bypass.bodies.find(body=>body.stock==='delivery-ramp'),{x:670,y:350,angle:.12});const bypassWorld=simulate(createWorld(bypass),9);assert.equal(bypassWorld.won,false,'Route around zone must fail');assert.deepEqual(bypassWorld.bodies.find(body=>body.id==='delivery-ball').transformedZones,[]);assert.equal(insideBucket(bypassWorld,'delivery-ball','stone-bucket'),true,'Bypass must still reach the bucket');
    const reset=new Workshop(solved),first=solveTime(reset.world);assert.equal(first,6.866666666666666);reset.reset();assert.equal(reset.world.bodies.find(body=>body.id==='delivery-ball').material,'cork');assert.deepEqual(reset.world.bodies.find(body=>body.id==='delivery-ball').transformedZones,[]);assert.equal(solveTime(reset.world),first,'Rock Delivery reset must preserve solve time');
  }
  if(transformationLevels.has(level.id)){
    const test=transformationLevels.get(level.id),reference=createWorld(solved),transforms=[],moments=(test.milestones??[]).map(([message,time,predicate])=>({message,time,predicate,actual:null}));let wonAt=null,transformVelocity=null,reversalAt=null,ropeBlocked=false;for(let frame=1;frame<=test.seconds*120;frame++){const events=stepWorld(reference),materials=events.filter(event=>event.kind==='transform').map(event=>event.material),ball=reference.bodies.find(body=>body.id===test.ball);transforms.push(...materials);if(materials.length&&transformVelocity===null)transformVelocity=ball.vy;if(transformVelocity!==null&&reversalAt===null&&ball.vy>=0)reversalAt=frame/120;if(test.rope&&!reference.won&&reference.connections.find(connection=>connection.id===test.rope).blocked)ropeBlocked=true;for(const moment of moments)if(moment.actual===null&&moment.predicate(reference,events))moment.actual=frame/120;if(reference.won&&wonAt===null)wonAt=frame/120;}
    const transformed=reference.bodies.find(body=>body.id===test.ball);assert.equal(wonAt,test.wonAt);assert.deepEqual(transforms,test.transforms);assert.equal(transformed.material,test.transforms.at(-1));if(test.zones)assert.deepEqual(transformed.transformedZones,test.zones);assert.deepEqual(overlapPairs(createWorld(solved),test.includeSensors),[]);assert.equal(ropeBlocked,false,`${level.name} rope must remain unblocked through the win`);
    for(const moment of moments)assert.equal(moment.actual,moment.time,moment.message);if(test.reverses){assert.ok(transformVelocity<0,'Transformation must preserve the balloon upward velocity');assert.notEqual(reversalAt,null,'Steel gravity must reverse the balloon downward');if(test.reversalAt!==undefined)assert.equal(reversalAt,test.reversalAt,'Balloon reversal time changed');}
    if(test.baseline){const baseline=simulate(createWorld(parseLevel(level)),test.seconds);for(const [message,predicate] of test.baseline)assert.equal(predicate(baseline),true,message);}
    for(const [message,mutate] of test.ablations){const ablation=structuredClone(solved);mutate(ablation);assert.equal(simulate(createWorld(ablation),test.seconds).won,false,message);}
    const positionDelta=test.positionDelta??8,variants=test.variants??[['x',-positionDelta],['x',positionDelta],['y',-positionDelta],['y',positionDelta],['angle',-(test.angleDelta??.02)],['angle',test.angleDelta??.02]];for(const [field,delta] of variants){const nearby=structuredClone(solved);nearby.bodies.find(body=>body.stock===test.stock)[field]+=delta;const nearbyWorld=createWorld(nearby);let nearbyRopeBlocked=false;assert.deepEqual(overlapPairs(nearbyWorld,test.includeSensors),[]);const nearbyWin=solveTime(nearbyWorld,test.seconds,world=>{if(test.rope&&world.connections.find(connection=>connection.id===test.rope).blocked)nearbyRopeBlocked=true;});assert.notEqual(nearbyWin,null,`${level.name} nearby ${field} ${delta} must win`);assert.equal(nearbyRopeBlocked,false,`${level.name} nearby ${field} ${delta} must preserve its rope route`);}
    const reset=new Workshop(solved),first=solveTime(reset.world,test.seconds);assert.equal(first,test.wonAt);reset.reset();assert.equal(reset.world.bodies.find(body=>body.id===test.ball).material,test.original);assert.equal(solveTime(reset.world,test.seconds),first,`${level.name} reset must preserve solve time`);
  }
  if(level.id==='counterweight-checkpoint'){
    const timeline=source=>{const testWorld=createWorld(source),holdStarts=[];let enteredAt=null,wonAt=null,ropeBlockedBeforeWin=false,maxHeld=0,previousHeld=0;for(let frame=1;frame<=10*120;frame++){stepWorld(testWorld);const lift=testWorld.bodies.find(body=>body.id==='lift-car'),rope=testWorld.connections.find(connection=>connection.id==='elevator-rope'),inside=Math.abs(lift.x-500)<=85&&Math.abs(lift.y-435)<=45;if(inside&&enteredAt===null)enteredAt=frame/120;if(testWorld.goalHeld>0&&previousHeld===0)holdStarts.push(frame/120);previousHeld=testWorld.goalHeld;maxHeld=Math.max(maxHeld,testWorld.goalHeld);if(!testWorld.won&&rope?.blocked)ropeBlockedBeforeWin=true;if(testWorld.won&&wonAt===null)wonAt=frame/120;}return{enteredAt,holdStarts,wonAt,maxHeld,ropeBlockedBeforeWin,finalLiftY:testWorld.bodies.find(body=>body.id==='lift-car').y,finalWeightY:testWorld.bodies.find(body=>body.id==='drop-weight')?.y??null,finalCrateY:testWorld.bodies.find(body=>body.id==='placed-stop-crate')?.y??null};};
    const baseline=timeline(authored),reference=timeline(solved),rope=authored.connections.find(connection=>connection.id==='elevator-rope'),stock=authored.inventory.find(entry=>entry.id==='stop-crate');assert.equal(rope.length,1563.028513935223,'Counterweight Checkpoint rope length changed');assert.equal(authored.goal.delay,.5,'Counterweight Checkpoint must require a half-second hold');assert.deepEqual([stock.part.w,stock.part.h,stock.part.resizable,stock.quantity],[180,140,false,1],'Counterweight Checkpoint must supply one fixed-size crate');assert.equal(baseline.enteredAt,.825,'Empty-bin elevator must visibly cross the landing');assert.equal(baseline.maxHeld,.15,'Empty-bin landing hold must remain too brief');assert.equal(baseline.wonAt,null,'Empty-bin elevator must overshoot and fail');assert.deepEqual(reference,{enteredAt:.825,holdStarts:[.825,2.183333333333333],wonAt:2.675,maxHeld:.5000000000000007,ropeBlockedBeforeWin:false,finalLiftY:436.6785229389255,finalWeightY:765.7164575574081,finalCrateY:870.3996346469725},'Counterweight Checkpoint timeline changed');assert.deepEqual(overlapPairs(createWorld(solved),true),[],'Counterweight Checkpoint must start without overlaps, including sensors');
    const ablations=[['stop crate',source=>{source.bodies=source.bodies.filter(body=>body.stock!=='stop-crate');}],['rope',source=>{source.connections=[];}],['heavy counterweight',source=>{source.bodies.find(body=>body.id==='drop-weight').material='cork';}],['counterweight',source=>{source.bodies=source.bodies.filter(body=>body.id!=='drop-weight');source.connections=[];}],['crate in the weight shaft',source=>{source.bodies.find(body=>body.stock==='stop-crate').x=850;}]];for(const [name,mutate] of ablations){const ablation=structuredClone(solved);mutate(ablation);assert.equal(timeline(ablation).wonAt,null,`Counterweight Checkpoint must need its ${name}`);}
    for(const [field,delta] of [['x',-8],['x',8],['y',-6],['y',6],['angle',-.03],['angle',.03]]){const nearby=structuredClone(solved);nearby.bodies.find(body=>body.stock==='stop-crate')[field]+=delta;const nearbyWorld=createWorld(nearby);assert.deepEqual(overlapPairs(nearbyWorld,true),[],`Counterweight Checkpoint nearby ${field} ${delta} must not overlap`);const nearbyResult=timeline(nearby);assert.equal(nearbyResult.wonAt,2.675,`Counterweight Checkpoint nearby ${field} ${delta} solve time changed`);assert.equal(nearbyResult.ropeBlockedBeforeWin,false,`Counterweight Checkpoint nearby ${field} ${delta} must keep its rope valid`);assert.ok(Math.abs(nearbyResult.finalLiftY-reference.finalLiftY)<.02,`Counterweight Checkpoint nearby ${field} ${delta} must settle at the same landing height`);}
    const reset=new Workshop(solved),first=solveTime(reset.world,10);assert.equal(first,2.675);reset.reset();assert.equal(reset.world.goalHeld,0);assert.equal(reset.world.connections.find(connection=>connection.id==='elevator-rope').blocked,false);assert.equal(solveTime(reset.world,10),first,'Counterweight Checkpoint reset must preserve solve time');
  }
  if(level.id==='stone-age-seesaw'){
    const timeline=source=>{const testWorld=createWorld(source);let transformAt=null,reversalAt=null,bellAt=null,wonAt=null,minDeliveryBallY=Infinity,minAngle=Infinity,maxAngle=-Infinity;for(let frame=1;frame<=8*120;frame++){const events=stepWorld(testWorld),ball=testWorld.bodies.find(body=>body.id==='delivery-ball'),seesaw=testWorld.bodies.find(body=>body.id==='seesaw'),bell=testWorld.bodies.find(body=>body.id==='finish-bell');if(events.some(event=>event.kind==='transform')&&transformAt===null)transformAt=frame/120;if(seesaw?.angle<0&&reversalAt===null)reversalAt=frame/120;if(bell.state==='rung'&&bellAt===null)bellAt=frame/120;if(testWorld.won&&wonAt===null)wonAt=frame/120;minDeliveryBallY=Math.min(minDeliveryBallY,ball.y);if(seesaw){minAngle=Math.min(minAngle,seesaw.angle);maxAngle=Math.max(maxAngle,seesaw.angle);}}const counterweight=testWorld.bodies.find(body=>body.id==='cork-counterweight');return{transformAt,reversalAt,bellAt,wonAt,minDeliveryBallY,minAngle,maxAngle,counterweightMaterial:counterweight?.material??null,transformedZones:counterweight?.transformedZones??[]};};
    const baseline=timeline(authored),reference=timeline(solved),stock=authored.inventory.find(entry=>entry.id==='stone-zone-stock');assert.deepEqual([stock.part.w,stock.part.h,stock.part.outputMaterial,stock.part.resizable,stock.quantity],[150,130,'steel',false,1],'Stone Age Seesaw must supply one fixed-size Turn to Stone zone');assert.equal(baseline.transformAt,null,'Empty-bin counterweight must remain cork');assert.equal(baseline.reversalAt,null,'Empty-bin seesaw must never reverse');assert.equal(baseline.wonAt,null,'Empty-bin basketball must miss the bell');assert.ok(baseline.minDeliveryBallY>700,'Empty-bin basketball must never rise toward the bell');assert.deepEqual({transformAt:reference.transformAt,reversalAt:reference.reversalAt,bellAt:reference.bellAt,wonAt:reference.wonAt},{transformAt:.5916666666666667,reversalAt:1.125,bellAt:1.5583333333333333,wonAt:1.5583333333333333},'Stone Age Seesaw event sequence changed');assert.equal(reference.counterweightMaterial,'steel');assert.deepEqual(reference.transformedZones,['placed-stone-zone']);assert.ok(reference.maxAngle>.4&&reference.minAngle<-.7,'Stone impact must decisively reverse the seesaw');assert.deepEqual(overlapPairs(createWorld(solved),true),[],'Stone Age Seesaw must start without overlaps, including its sensor zone');
    const ablations=[['stone zone',source=>{source.bodies=source.bodies.filter(body=>body.stock!=='stone-zone-stock');}],['steel transformation',source=>{source.bodies.find(body=>body.stock==='stone-zone-stock').outputMaterial='cork';}],['zone on the counterweight path',source=>{source.bodies.find(body=>body.stock==='stone-zone-stock').x=700;}],['counterweight',source=>{source.bodies=source.bodies.filter(body=>body.id!=='cork-counterweight');}],['seesaw',source=>{source.bodies=source.bodies.filter(body=>body.id!=='seesaw');}],['pinned seesaw',source=>{const seesaw=source.bodies.find(body=>body.id==='seesaw');seesaw.fixed=true;seesaw.pinned=false;}]];for(const [name,mutate] of ablations){const ablation=structuredClone(solved);mutate(ablation);assert.equal(timeline(ablation).wonAt,null,`Stone Age Seesaw must need its ${name}`);}
    for(const [field,delta] of [['x',-20],['x',-10],['x',10],['x',20],['y',-20],['y',-10],['y',10],['y',20],['angle',-.1],['angle',-.05],['angle',.05],['angle',.1]]){const nearby=structuredClone(solved);nearby.bodies.find(body=>body.stock==='stone-zone-stock')[field]+=delta;const nearbyWorld=createWorld(nearby);assert.deepEqual(overlapPairs(nearbyWorld,true),[],`Stone Age Seesaw nearby ${field} ${delta} must not overlap`);assert.equal(timeline(nearby).wonAt,reference.wonAt,`Stone Age Seesaw nearby ${field} ${delta} solve time changed`);}
    const reset=new Workshop(solved),first=solveTime(reset.world,8);assert.equal(first,1.5583333333333333);reset.reset();assert.equal(reset.world.bodies.find(body=>body.id==='cork-counterweight').material,'cork');assert.deepEqual(reset.world.bodies.find(body=>body.id==='cork-counterweight').transformedZones,[]);assert.equal(reset.world.bodies.find(body=>body.id==='seesaw').angle,0);assert.notEqual(reset.world.bodies.find(body=>body.id==='finish-bell').state,'rung');assert.equal(solveTime(reset.world,8),first,'Stone Age Seesaw reset must preserve solve time');
  }
  if(level.id==='stone-cold-chain'){
    const timeline=source=>{const testWorld=createWorld(source),transformations=[];let transformAt=null,firstToppleAt=null,bridgeToppleAt=null,secondBankAt=null,switchAt=null,wonAt=null;for(let frame=1;frame<=10*120;frame++){const events=stepWorld(testWorld),first=testWorld.bodies.find(body=>body.id==='domino-a'),bridge=testWorld.bodies.find(body=>body.id==='placed-missing-domino'),second=testWorld.bodies.find(body=>body.id==='domino-d'),trigger=testWorld.bodies.find(body=>body.id==='finish-switch'),transformed=events.filter(event=>event.kind==='transform');transformations.push(...transformed.map(event=>event.material));if(transformed.length&&transformAt===null)transformAt=frame/120;if(Math.abs(first.angle)>.2&&firstToppleAt===null)firstToppleAt=frame/120;if(bridge&&Math.abs(bridge.angle)>.2&&bridgeToppleAt===null)bridgeToppleAt=frame/120;if(Math.abs(second.angle)>.2&&secondBankAt===null)secondBankAt=frame/120;if(trigger.state==='on'&&switchAt===null)switchAt=frame/120;if(testWorld.won&&wonAt===null)wonAt=frame/120;}return{transformAt,firstToppleAt,bridgeToppleAt,secondBankAt,switchAt,wonAt,transformations};};
    const baseline=timeline(authored),reference=timeline(solved),stock=authored.inventory.find(entry=>entry.id==='missing-domino');assert.deepEqual([stock.part.w,stock.part.h,stock.part.resizable,stock.quantity],[24,150,false,1],'Stone-Cold Chain must supply exactly one fixed-size upright domino');assert.equal(baseline.wonAt,null,'Empty-bin first bank must stop at the missing link');assert.equal(baseline.secondBankAt,null,'Empty-bin wave must not reach the second bank');assert.deepEqual(reference,{transformAt:.6,firstToppleAt:1.1083333333333334,bridgeToppleAt:1.9833333333333334,secondBankAt:2.3833333333333333,switchAt:3.05,wonAt:3.05,transformations:['steel']},'Stone-Cold Chain event sequence changed');assert.deepEqual(overlapPairs(createWorld(solved),true),[],'Stone-Cold Chain must start without overlaps, including sensors');
    const ablations=[['bridge',source=>{source.bodies=source.bodies.filter(body=>body.stock!=='missing-domino');}],['stone zone',source=>{source.bodies=source.bodies.filter(body=>body.id!=='stone-zone');}],['steel transformation',source=>{source.bodies.find(body=>body.id==='stone-zone').outputMaterial='cork';}],['upright bridge',source=>{source.bodies.find(body=>body.stock==='missing-domino').angle=Math.PI/2;}],['bridge placement',source=>{source.bodies.find(body=>body.stock==='missing-domino').x=970;}]];for(const [name,mutate] of ablations){const ablation=structuredClone(solved);mutate(ablation);assert.equal(timeline(ablation).wonAt,null,`Stone-Cold Chain must need its ${name}`);}
    for(const [field,delta] of [['x',-6],['x',6],['y',-6],['y',6],['angle',-.03],['angle',.03]]){const nearby=structuredClone(solved);nearby.bodies.find(body=>body.stock==='missing-domino')[field]+=delta;const nearbyWorld=createWorld(nearby);assert.deepEqual(overlapPairs(nearbyWorld,true),[],`Stone-Cold Chain nearby ${field} ${delta} must not overlap`);assert.notEqual(timeline(nearby).wonAt,null,`Stone-Cold Chain nearby ${field} ${delta} must win`);}
    const reset=new Workshop(solved),first=solveTime(reset.world,10);assert.equal(first,3.05);reset.reset();assert.equal(reset.world.bodies.find(body=>body.id==='starter-marble').material,'cork');assert.deepEqual(reset.world.bodies.find(body=>body.id==='starter-marble').transformedZones,[]);assert.ok(reset.world.bodies.filter(body=>body.kind==='box').every(body=>body.angle===0),'Reset must stand every domino upright');assert.equal(solveTime(reset.world,10),first,'Stone-Cold Chain reset must preserve solve time');
  }
  if(level.id==='blow-the-bell'){
    const timeline=source=>{const testWorld=createWorld(source);let fanContactAt=null,bellAt=null,wonAt=null,ropeBlockedBeforeWin=false,maxBallX=-Infinity,minBallY=Infinity;for(let frame=1;frame<=8*120;frame++){stepWorld(testWorld);const ball=testWorld.bodies.find(body=>body.id==='pendulum-ball'),bell=testWorld.bodies.find(body=>body.id==='swing-bell'),rope=testWorld.connections.find(connection=>connection.id==='pendulum-rope');maxBallX=Math.max(maxBallX,ball.x);minBallY=Math.min(minBallY,ball.y);if(fanContactAt===null&&ball.vx>1)fanContactAt=frame/120;if(bell.state==='rung'&&bellAt===null)bellAt=frame/120;if(!testWorld.won&&rope?.blocked)ropeBlockedBeforeWin=true;if(testWorld.won&&wonAt===null)wonAt=frame/120;}return{fanContactAt,bellAt,wonAt,ropeBlockedBeforeWin,maxBallX,minBallY};};
    const baseline=timeline(authored),reference=timeline(solved),rope=level.connections.find(connection=>connection.id==='pendulum-rope'),stock=authored.inventory.find(entry=>entry.id==='crosswind');assert.equal(rope.length,350,'Blow the Bell needs a taut 350-unit rope');assert.deepEqual([stock.part.w,stock.part.h,stock.part.resizable],[70,70,false],'Blow the Bell inventory must contain one fixed-size fan');assert.equal(stock.quantity,1);
    assert.equal(baseline.wonAt,null,'Empty-bin pendulum must fail');assert.equal(baseline.fanContactAt,null,'Empty-bin pendulum must not receive fan force');assert.ok(Math.abs(baseline.maxBallX-800)<.1&&Math.abs(baseline.minBallY-500)<.1,'Empty-bin pendulum must remain motionless');assert.deepEqual(reference,{fanContactAt:.008333333333333333,bellAt:.7916666666666666,wonAt:.7916666666666666,ropeBlockedBeforeWin:false,maxBallX:997.3631445405139,minBallY:439.0649774799834},'Blow the Bell pendulum timeline changed');assert.deepEqual(overlapPairs(createWorld(solved),true),[],'Blow the Bell must start without overlaps, including sensors');
    const ablations=[['active fan',source=>{source.bodies.find(body=>body.stock==='crosswind').on=false;}],['full fan power',source=>{source.bodies.find(body=>body.stock==='crosswind').power=1;}],['fan direction',source=>{source.bodies.find(body=>body.stock==='crosswind').angle=Math.PI;}],['rope',source=>{source.connections=[];}],['taut rope',source=>{source.connections.find(connection=>connection.id==='pendulum-rope').length=450;}]];for(const [name,mutate] of ablations){const ablation=structuredClone(solved);mutate(ablation);assert.equal(timeline(ablation).wonAt,null,`Blow the Bell must need its ${name}`);}
    for(const [field,delta] of [['x',-8],['x',8],['y',-8],['y',8],['angle',-.03],['angle',.03]]){const nearby=structuredClone(solved);nearby.bodies.find(body=>body.stock==='crosswind')[field]+=delta;const nearbyWorld=createWorld(nearby);assert.deepEqual(overlapPairs(nearbyWorld,true),[],`Blow the Bell nearby ${field} ${delta} must not overlap`);const nearbyResult=timeline(nearby);assert.notEqual(nearbyResult.wonAt,null,`Blow the Bell nearby ${field} ${delta} must win`);assert.equal(nearbyResult.ropeBlockedBeforeWin,false,`Blow the Bell nearby ${field} ${delta} must keep its rope valid`);}
    const reset=new Workshop(solved),first=solveTime(reset.world,8);assert.equal(first,.7916666666666666);reset.reset();assert.equal(solveTime(reset.world,8),first,'Blow the Bell reset must preserve solve time');
  }
  if(level.id==='rocket-bank-shot'){
    const timeline=source=>{const testWorld=createWorld(source);let firedAt=null,springAt=null,bellAt=null,wonAt=null;for(let frame=1;frame<=8*120;frame++){const events=stepWorld(testWorld),rocket=testWorld.bodies.find(body=>body.id==='ricochet-rocket'),bell=testWorld.bodies.find(body=>body.id==='bank-shot-bell');if(rocket.state==='fired'&&firedAt===null)firedAt=frame/120;if(events.some(event=>event.kind==='trampoline')&&springAt===null)springAt=frame/120;if(bell.state==='rung'&&bellAt===null)bellAt=frame/120;if(testWorld.won&&wonAt===null)wonAt=frame/120;}return{firedAt,springAt,bellAt,wonAt};};
    const baseline=timeline(parseLevel(level)),reference=timeline(solved);assert.equal(level.environment.gravity,0,'Rocket Bank Shot must remain a zero-gravity puzzle');assert.equal(baseline.firedAt,.008333333333333333,'Empty-bin rocket must still move under thrust');assert.equal(baseline.springAt,null,'Empty-bin run must have no spring impact');assert.equal(baseline.wonAt,null,'Empty-bin rocket must miss the bell');assert.deepEqual(reference,{firedAt:.008333333333333333,springAt:.8916666666666667,bellAt:1.075,wonAt:1.075},'Rocket Bank Shot event timeline changed');assert.deepEqual(overlapPairs(createWorld(solved),true),[],'Rocket Bank Shot must start without overlaps');
    const ablations=[['spring',source=>{source.bodies=source.bodies.filter(body=>body.stock!=='spring-mirror');}],['angled spring',source=>{source.bodies.find(body=>body.stock==='spring-mirror').angle=0;}],['spring direction',source=>{source.bodies.find(body=>body.stock==='spring-mirror').angle=-.42;}],['rocket power',source=>{source.bodies.find(body=>body.id==='ricochet-rocket').power=0;}]];for(const [name,mutate] of ablations){const ablation=structuredClone(solved);mutate(ablation);assert.equal(timeline(ablation).wonAt,null,`Rocket Bank Shot must need its ${name}`);}
    for(const [field,delta] of [['x',-8],['x',8],['y',-8],['y',8],['angle',-.03],['angle',.03]]){const nearby=structuredClone(solved);nearby.bodies.find(body=>body.stock==='spring-mirror')[field]+=delta;const nearbyWorld=createWorld(nearby);assert.deepEqual(overlapPairs(nearbyWorld,true),[]);assert.notEqual(solveTime(nearbyWorld,8),null,`Rocket Bank Shot nearby ${field} ${delta} must win`);}
    const reset=new Workshop(solved),first=solveTime(reset.world,8);assert.equal(first,1.075);reset.reset();assert.equal(solveTime(reset.world,8),first,'Rocket Bank Shot reset must preserve solve time');
  }
  if(level.id==='rocket-counterweight'){
    const baseline=createWorld(parseLevel(level));simulate(baseline,12);assert.notEqual(baseline.bodies.find(body=>body.id==='launch-switch').state,'on','Empty bin must not flip the switch');assert.notEqual(baseline.bodies.find(body=>body.id==='down-rocket').state,'fired','Empty bin must not fire the rocket');
    const reference=createWorld(solved);let switchAt=null,firedAt=null,wonAt=null;for(let frame=1;frame<=12*120;frame++){stepWorld(reference);if(reference.bodies.find(body=>body.id==='launch-switch').state==='on'&&switchAt===null)switchAt=frame/120;if(reference.bodies.find(body=>body.id==='down-rocket').state==='fired'&&firedAt===null)firedAt=frame/120;if(reference.won&&wonAt===null)wonAt=frame/120;}
    assert.equal(switchAt,2.4,'Ramp must deliver the ball to the switch');assert.equal(firedAt,2.408333333333333,'Wire must fire the rocket after the switch');assert.equal(wonAt,2.9166666666666665,'Rocket counterweight must ring the bell');assert.deepEqual(overlapPairs(createWorld(solved)),[],'Rocket Counterweight must start without solid overlaps');
    const ablations=[['wire',level=>{level.connections=level.connections.filter(connection=>connection.kind!=='wire');}],['rope',level=>{level.connections=level.connections.filter(connection=>connection.kind!=='rope');}],['rocket power',level=>{level.bodies.find(body=>body.id==='down-rocket').power=0;}]];
    for(const [name,mutate] of ablations){const ablation=structuredClone(solved);mutate(ablation);assert.equal(simulate(createWorld(ablation),12).won,false,`Rocket Counterweight must need its ${name}`);}
    for(const [field,delta] of [['x',-8],['x',8],['y',-8],['y',8],['angle',-.03],['angle',.03]]){const nearby=structuredClone(solved);nearby.bodies.find(body=>body.stock==='trigger-ramp')[field]+=delta;const nearbyWorld=createWorld(nearby);assert.deepEqual(overlapPairs(nearbyWorld),[]);assert.notEqual(solveTime(nearbyWorld,12),null,`Rocket Counterweight nearby ${field} ${delta} must win`);}
    const reset=new Workshop(solved),first=solveTime(reset.world,12);assert.equal(first,wonAt);reset.reset();assert.equal(solveTime(reset.world,12),first,'Rocket Counterweight reset must preserve solve time');
  }
  if(level.id==='flywheel-express'){
    const baseline=createWorld(parseLevel(level));simulate(baseline,10);const baselineWheel=baseline.bodies.find(body=>body.id==='launch-wheel'),baselineRider=baseline.bodies.find(body=>body.id==='wheel-rider');assert.notEqual(baseline.bodies.find(body=>body.id==='flywheel-switch').state,'on','Empty bin must not flip the switch');assert.equal(baseline.bodies.find(body=>body.id==='flywheel-motor').active,false,'Empty bin must not power the motor');assert.equal(baselineWheel.omega,0,'Empty-bin flywheel must remain stationary');assert.ok(Math.abs(baselineRider.x-baselineWheel.x)<1&&baselineRider.y<baselineWheel.y&&Math.abs(baselineRider.vx)+Math.abs(baselineRider.vy)+Math.abs(baselineRider.omega)<1e-6,'Rider must balance on the stationary flywheel');
    const reference=createWorld(solved);let switchAt=null,motorAt=null,wonAt=null;for(let frame=1;frame<=10*120;frame++){stepWorld(reference);if(reference.bodies.find(body=>body.id==='flywheel-switch').state==='on'&&switchAt===null)switchAt=frame/120;if(reference.bodies.find(body=>body.id==='flywheel-motor').active&&motorAt===null)motorAt=frame/120;if(reference.won&&wonAt===null)wonAt=frame/120;}
    assert.equal(switchAt,2.3916666666666666,'Ramp must deliver the ball to the switch');assert.equal(motorAt,2.4,'Wire must power the motor after the switch');assert.equal(wonAt,3.1,'Flywheel must launch its rider into the bell');assert.deepEqual(overlapPairs(createWorld(solved)),[],'Flywheel Express must start without solid overlaps');
    const ablations=[['wire',level=>{level.connections=level.connections.filter(connection=>connection.kind!=='wire');}],['belt',level=>{level.connections=level.connections.filter(connection=>connection.kind!=='belt');}],['motor power',level=>{level.bodies.find(body=>body.id==='flywheel-motor').power=0;}]];for(const [name,mutate] of ablations){const ablation=structuredClone(solved);mutate(ablation);assert.equal(simulate(createWorld(ablation),10).won,false,`Flywheel Express must need its ${name}`);}
    for(const [field,delta] of [['x',-8],['x',8],['y',-8],['y',8],['angle',-.03],['angle',.03]]){const nearby=structuredClone(solved);nearby.bodies.find(body=>body.stock==='flywheel-trigger-ramp')[field]+=delta;const nearbyWorld=createWorld(nearby);assert.deepEqual(overlapPairs(nearbyWorld),[]);assert.notEqual(solveTime(nearbyWorld,10),null,`Flywheel Express nearby ${field} ${delta} must win`);}
    const reset=new Workshop(solved),first=solveTime(reset.world,10);assert.equal(first,wonAt);reset.reset();assert.equal(solveTime(reset.world,10),first,'Flywheel Express reset must preserve solve time');
  }
  console.log(`PASS ${level.name}`);
}
console.log('PASS gravity, stacks, thin collisions, belt chains, ropes, material zones, switches, fixed-size inventory, strict imports, undo, puzzle solutions and JSON round trips');
